// Hybrid treatment structure — Paket 3.
// Each category page lists anchor-linkable sections; some sections point to a
// standalone SEO subpage (subSlug), others exist only as an anchor section.
// Durations/costs are medically plausible placeholders pending client approval
// (see AGENTS.md "Content Approval Status").

export const CATEGORIES = {
  botulinumtoxin: {
    slug: 'botulinumtoxin',
    canonicalSlug: 'behandlung-mimischer-falten',
    image_url: 'https://media.base44.com/images/public/6a6b131f6cc49b3ee60e929e/9147ba321_generated_image.png',
    title_de: 'Botulinumtoxin.',
    title_en: 'Botulinum toxin.',
    accent_de: 'Mimik im Gleichgewicht.',
    accent_en: 'Expression, balanced.',
    lead_de: 'Die Behandlung mimischer Falten wirkt gezielt auf überaktive Muskulatur und glättet Ausdrucksfalten, ohne die natürliche Mimik zu verändern.',
    lead_en: 'Treatment of mimic wrinkles works precisely on overactive muscles and smooths expression lines without altering natural facial movement.',
    seoDesc_de: 'Botulinumtoxin-Behandlungen in Zürich: Stirnfalten, Zornesfalte, Krähenfüsse, Brow Lift, Masseter und mehr — ärztlich durchgeführt, individuell dosiert.',
    seoDesc_en: 'Botulinum toxin treatments in Zurich: frown lines, forehead lines, crow\'s feet, brow lift, masseter and more — physician-led, individually dosed.',
    sections: [
      {
        id: 'stirnfalten', subSlug: 'stirnfalten',
        title_de: 'Stirnfalten', title_en: 'Forehead lines',
        lead_de: 'Horizontale Fältchen auf der Stirn entstehen durch wiederholte Anspannung des Stirnmuskels beim Anheben der Augenbrauen.',
        lead_en: 'Horizontal forehead lines form through repeated tension of the frontalis muscle when raising the brows.',
        goals_de: ['Glättung horizontaler Stirnfalten', 'Natürliche Beweglichkeit der Augenbrauen erhalten', 'Vorbeugung tiefer eingegrabener Linien'],
        goals_en: ['Smoothing horizontal forehead lines', 'Preserving natural brow movement', 'Preventing deeply etched lines'],
        duration_de: '15–20 Minuten', duration_en: '15–20 minutes',
      },
      {
        id: 'zornesfalte', subSlug: 'zornesfalte',
        title_de: 'Zornesfalte', title_en: 'Glabellar frown line',
        lead_de: 'Die senkrechte Falte zwischen den Augenbrauen entsteht durch den Musculus corrugator und kann einen unbeabsichtigt ernsten Ausdruck erzeugen.',
        lead_en: 'The vertical line between the brows is formed by the corrugator muscle and can create an unintentionally stern expression.',
        goals_de: ['Auflösung eines strengen oder erschöpften Ausdrucks', 'Glättung der senkrechten Zornesfalte', 'Harmonischeres Zusammenspiel der Augenbrauenmuskulatur'],
        goals_en: ['Softening a stern or tired expression', 'Smoothing the vertical frown line', 'A more harmonious interplay of brow muscles'],
        duration_de: '15–20 Minuten', duration_en: '15–20 minutes',
      },
      {
        id: 'kraehenfuesse', subSlug: 'kraehenfuesse',
        title_de: 'Krähenfüsse', title_en: 'Crow\'s feet',
        lead_de: 'Feine Fältchen am äusseren Augenwinkel entstehen durch die Aktivität des Musculus orbicularis oculi, insbesondere beim Lachen.',
        lead_en: 'Fine lines at the outer corner of the eye result from the activity of the orbicularis oculi muscle, particularly when smiling.',
        goals_de: ['Glättung feiner Linien am äusseren Augenwinkel', 'Wacher, offener Blick', 'Natürliches Lachen bleibt erhalten'],
        goals_en: ['Smoothing fine lines at the outer eye corner', 'A brighter, more open gaze', 'Natural smiling is preserved'],
        duration_de: '15–20 Minuten', duration_en: '15–20 minutes',
      },
      {
        id: 'browlift',
        title_de: 'Brow Lift', title_en: 'Brow lift',
        lead_de: 'Durch gezielte Schwächung absenkender Muskelanteile lässt sich die Augenbraue minimalinvasiv leicht anheben.',
        lead_en: 'By selectively weakening depressor muscles, the brow can be lifted slightly with a minimally invasive approach.',
        goals_de: ['Leichte Anhebung der äusseren Augenbraue', 'Offenerer Blick ohne chirurgischen Eingriff', 'Ausgewogene Brauenform'],
        goals_en: ['Slight lift of the outer brow', 'A more open gaze without surgery', 'A balanced brow shape'],
        duration_de: '15–20 Minuten', duration_en: '15–20 minutes',
      },
      {
        id: 'bunny-lines',
        title_de: 'Bunny Lines', title_en: 'Bunny lines',
        lead_de: 'Schräge Fältchen am Nasenrücken entstehen durch Anspannen des Musculus nasalis, oft begleitend zur Stirnbehandlung sichtbar.',
        lead_en: 'Diagonal lines across the nasal bridge form through activity of the nasalis muscle, often becoming visible alongside forehead treatment.',
        goals_de: ['Glättung der Fältchen am Nasenrücken', 'Harmonisches Gesamtbild bei Behandlung der oberen Gesichtshälfte', 'Fein abgestimmte, niedrige Dosierung'],
        goals_en: ['Smoothing lines across the nasal bridge', 'A harmonious result across the upper face', 'Finely calibrated, low dosing'],
        duration_de: '10–15 Minuten', duration_en: '10–15 minutes',
      },
      {
        id: 'gummy-smile',
        title_de: 'Gummy Smile', title_en: 'Gummy smile',
        lead_de: 'Ein stark sichtbares Zahnfleisch beim Lachen lässt sich durch feine Dosierung im Bereich der Lippenheber reduzieren.',
        lead_en: 'A prominent gum display when smiling can be reduced through fine dosing in the upper-lip elevator muscles.',
        goals_de: ['Ausgewogeneres Lächeln', 'Reduktion sichtbaren Zahnfleisches', 'Natürliche Lippenbeweglichkeit bleibt erhalten'],
        goals_en: ['A more balanced smile', 'Reduced visible gum tissue', 'Natural lip movement is preserved'],
        duration_de: '15 Minuten', duration_en: '15 minutes',
      },
      {
        id: 'pflastersteinkinn',
        title_de: 'Pflastersteinkinn', title_en: 'Cobblestone chin',
        lead_de: 'Die höckerige Struktur des Kinns beim Anspannen entsteht durch den Musculus mentalis und lässt sich gezielt glätten.',
        lead_en: 'The dimpled texture of the chin under tension is caused by the mentalis muscle and can be smoothed with targeted treatment.',
        goals_de: ['Glättere Kinnoberfläche bei Anspannung', 'Harmonischeres unteres Gesichtsdrittel', 'Dezente, natürlich wirkende Korrektur'],
        goals_en: ['A smoother chin surface under tension', 'A more harmonious lower face', 'A subtle, natural-looking correction'],
        duration_de: '10–15 Minuten', duration_en: '10–15 minutes',
      },
      {
        id: 'mundwinkel',
        title_de: 'Mundwinkel', title_en: 'Corners of the mouth',
        lead_de: 'Nach unten gezogene Mundwinkel können einen traurigen oder unzufriedenen Ausdruck erzeugen und lassen sich gezielt anheben.',
        lead_en: 'Downturned mouth corners can create a sad or dissatisfied expression and can be gently lifted.',
        goals_de: ['Freundlicherer Gesamtausdruck', 'Leichte Anhebung der Mundwinkel', 'Erhalt der natürlichen Sprech- und Kaufunktion'],
        goals_en: ['A friendlier overall expression', 'A slight lift of the mouth corners', 'Preserved natural speech and chewing function'],
        duration_de: '15 Minuten', duration_en: '15 minutes',
      },
      {
        id: 'masseter-zaehneknirschen', subSlug: 'masseter-zaehneknirschen',
        title_de: 'Masseter und Zähneknirschen', title_en: 'Masseter & teeth grinding',
        lead_de: 'Eine Überaktivität des Kaumuskels führt häufig zu Zähneknirschen, Kieferverspannung und einer breiteren Unterkiefer­kontur.',
        lead_en: 'Overactivity of the masseter muscle often causes teeth grinding, jaw tension, and a wider lower-jaw contour.',
        goals_de: ['Linderung von Kieferverspannung und Knirschen', 'Feinere, schlankere Unterkieferkontur', 'Entlastung der Kaumuskulatur'],
        goals_en: ['Relief from jaw tension and grinding', 'A finer, slimmer jawline contour', 'Reduced strain on the chewing muscles'],
        duration_de: '20–30 Minuten', duration_en: '20–30 minutes',
      },
      {
        id: 'schwitzen', subSlug: 'schwitzen',
        title_de: 'Übermässiges Schwitzen', title_en: 'Excessive sweating',
        lead_de: 'Bei übermässiger Schweissproduktion in Achseln, Händen oder Füssen reduziert die Behandlung gezielt die Aktivität der Schweissdrüsen.',
        lead_en: 'For excessive perspiration in the underarms, hands, or feet, treatment specifically reduces sweat gland activity.',
        goals_de: ['Deutliche Reduktion der Schweissproduktion', 'Mehr Sicherheit im Alltag', 'Wirkung über mehrere Monate'],
        goals_en: ['A significant reduction in sweat production', 'More confidence in everyday life', 'Effects lasting several months'],
        duration_de: '30–45 Minuten', duration_en: '30–45 minutes',
      },
    ],
  },
  'hyaluron-konturierung': {
    slug: 'hyaluron-konturierung',
    canonicalSlug: 'hyaluron-filler',
    image_url: 'https://media.base44.com/images/public/6a6b131f6cc49b3ee60e929e/aa2efde7c_generated_image.png',
    title_de: 'Hyaluron-Konturierung.',
    title_en: 'Hyaluronic contouring.',
    accent_de: 'Volumen und Form.',
    accent_en: 'Volume and form.',
    lead_de: 'Hyaluronsäure stellt Volumen wieder her und verfeinert Konturen — stets abgestimmt auf die individuelle Anatomie des Gesichts.',
    lead_en: 'Hyaluronic acid restores volume and refines contours — always tailored to individual facial anatomy.',
    seoDesc_de: 'Hyaluron-Konturierung in Zürich: Lippen, Wangen, Jawline, Kinn, Nasolabialfalte und mehr — individuell geplant, ärztlich injiziert.',
    seoDesc_en: 'Hyaluronic contouring in Zurich: lips, cheeks, jawline, chin, nasolabial folds and more — individually planned, physician-administered.',
    sections: [
      {
        id: 'lippenbehandlung', subSlug: 'lippenbehandlung',
        title_de: 'Lippenbehandlung', title_en: 'Lip treatment',
        lead_de: 'Feine Konturierung und dezenter Volumenaufbau lassen die Lippen ausgewogen und der Gesichtsproportion entsprechend wirken.',
        lead_en: 'Fine contouring and subtle volume enhancement create lips that appear balanced and proportionate to the face.',
        goals_de: ['Ausgewogene Lippenform', 'Dezenter, natürlicher Volumenaufbau', 'Erhalt der individuellen Lippenanatomie'],
        goals_en: ['A balanced lip shape', 'Subtle, natural volume', 'Preservation of individual lip anatomy'],
        duration_de: '30 Minuten', duration_en: '30 minutes',
      },
      {
        id: 'wangen-volumen',
        title_de: 'Wangen und Volumenaufbau', title_en: 'Cheeks & volume restoration',
        lead_de: 'Altersbedingter Volumenverlust in den Wangen lässt sich gezielt ausgleichen, um die Gesichtsstruktur wieder aufzurichten.',
        lead_en: 'Age-related volume loss in the cheeks can be specifically restored to re-support the facial structure.',
        goals_de: ['Wiederherstellung verlorenen Wangenvolumens', 'Angehobene, gestützte Gesichtskontur', 'Reduktion von Erschöpfungseindruck'],
        goals_en: ['Restoring lost cheek volume', 'A lifted, supported facial contour', 'A less tired-looking appearance'],
        duration_de: '30–45 Minuten', duration_en: '30–45 minutes',
      },
      {
        id: 'jawline', subSlug: 'jawline',
        title_de: 'Jawline', title_en: 'Jawline',
        lead_de: 'Eine gezielte Konturierung entlang des Unterkiefers definiert die Gesichtslinie und schafft ein klareres Profil.',
        lead_en: 'Targeted contouring along the lower jaw defines the facial line and creates a clearer profile.',
        goals_de: ['Klarere, definierte Kieferlinie', 'Ausgewogenes Profil im Seitenverlauf', 'Individuell abgestimmte Konturierung'],
        goals_en: ['A clearer, more defined jawline', 'A balanced side profile', 'Contouring tailored to the individual'],
        duration_de: '30–45 Minuten', duration_en: '30–45 minutes',
      },
      {
        id: 'kinnkontur',
        title_de: 'Kinnkontur', title_en: 'Chin contour',
        lead_de: 'Eine fein abgestimmte Kinnkonturierung stellt das Gleichgewicht zwischen Kinn, Lippen und Kieferlinie wieder her.',
        lead_en: 'Finely calibrated chin contouring restores balance between the chin, lips, and jawline.',
        goals_de: ['Ausgewogenes Verhältnis von Kinn und Profil', 'Feinere oder markantere Kinnform je nach Wunsch', 'Harmonisches unteres Gesichtsdrittel'],
        goals_en: ['A balanced relationship between chin and profile', 'A softer or more defined chin shape as desired', 'A harmonious lower face'],
        duration_de: '20–30 Minuten', duration_en: '20–30 minutes',
      },
      {
        id: 'nasolabialfalte',
        title_de: 'Nasolabialfalte', title_en: 'Nasolabial fold',
        lead_de: 'Die Falte zwischen Nasenflügel und Mundwinkel wird durch behutsamen Volumenausgleich in der Tiefe geglättet.',
        lead_en: 'The fold between the nose and mouth corner is softened through careful, deep volume restoration.',
        goals_de: ['Glättung der Nasolabialfalte', 'Natürlich wirkende Übergänge', 'Erhalt der Mimik beim Lachen'],
        goals_en: ['Softening the nasolabial fold', 'Natural-looking transitions', 'Preserved expression when smiling'],
        duration_de: '30 Minuten', duration_en: '30 minutes',
      },
      {
        id: 'marionettenfalten',
        title_de: 'Marionettenfalten', title_en: 'Marionette lines',
        lead_de: 'Die Falten von den Mundwinkeln zum Kinn hin lassen sich durch gezielte Unterspritzung deutlich mildern.',
        lead_en: 'The lines running from the mouth corners toward the chin can be visibly softened through targeted filling.',
        goals_de: ['Milderung der Falten am unteren Mundbereich', 'Freundlicherer Ausdruck', 'Harmonisches Zusammenspiel mit Kinn und Kieferlinie'],
        goals_en: ['Softening lines at the lower mouth area', 'A friendlier expression', 'Harmonious interplay with chin and jawline'],
        duration_de: '30 Minuten', duration_en: '30 minutes',
      },
      {
        id: 'gesichtsharmonisierung',
        title_de: 'Harmonisierung von Gesichtsproportionen', title_en: 'Facial proportion harmonisation',
        lead_de: 'Eine ganzheitliche Betrachtung mehrerer Gesichtsbereiche schafft ein ausgewogenes, stimmiges Gesamtbild.',
        lead_en: 'A holistic view of several facial areas creates a balanced, cohesive overall result.',
        goals_de: ['Stimmiges Verhältnis einzelner Gesichtsbereiche zueinander', 'Individueller Behandlungsplan über mehrere Zonen', 'Zurückhaltende, natürlich wirkende Umsetzung'],
        goals_en: ['A cohesive relationship between facial areas', 'An individual treatment plan spanning multiple zones', 'A restrained, natural-looking result'],
        duration_de: '45–60 Minuten', duration_en: '45–60 minutes',
      },
    ],
  },
  'hautqualitaet-regeneration': {
    slug: 'hautqualitaet-regeneration',
    canonicalSlug: 'skinbooster',
    image_url: 'https://media.base44.com/images/public/6a6b131f6cc49b3ee60e929e/178c12a52_generated_image.png',
    title_de: 'Hautqualität & Regeneration.',
    title_en: 'Skin quality & regeneration.',
    accent_de: 'Erneuerung von innen.',
    accent_en: 'Renewal from within.',
    lead_de: 'Diese Verfahren regen körpereigene Regenerationsprozesse an und verbessern Feuchtigkeit, Elastizität und Textur der Haut.',
    lead_en: 'These procedures stimulate the body\'s own regeneration processes and improve skin hydration, elasticity, and texture.',
    seoDesc_de: 'Hautqualität und Regeneration in Zürich: Skinbooster, Biostimulation, PRP und Microneedling — für Feuchtigkeit, Elastizität und Ausstrahlung.',
    seoDesc_en: 'Skin quality and regeneration in Zurich: skin boosters, biostimulation, PRP, and microneedling — for hydration, elasticity, and radiance.',
    sections: [
      {
        id: 'skinbooster', subSlug: null, canonical: 'skinbooster',
        title_de: 'Skinbooster', title_en: 'Skin booster',
        lead_de: 'Feine Hyaluronsäure wird flächig in die Haut eingebracht und bindet dort Feuchtigkeit über mehrere Wochen.',
        lead_en: 'Fine hyaluronic acid is distributed across the skin, binding moisture over several weeks.',
        goals_de: ['Verbesserte Hautfeuchtigkeit und Elastizität', 'Feinerer, ebenmässigerer Teint', 'Sanfter Frischeeffekt ohne Volumenzunahme'],
        goals_en: ['Improved skin hydration and elasticity', 'A finer, more even complexion', 'A gentle freshness without added volume'],
        duration_de: '30–45 Minuten', duration_en: '30–45 minutes',
      },
      {
        id: 'biostimulation', subSlug: null, canonical: 'biostimulation',
        title_de: 'Biostimulation', title_en: 'Biostimulation',
        lead_de: 'Biostimulatoren regen die körpereigene Kollagenproduktion an und verbessern die Hautstruktur über mehrere Monate.',
        lead_en: 'Biostimulators activate the body\'s own collagen production, improving skin structure over several months.',
        goals_de: ['Anregung körpereigener Kollagenbildung', 'Verbesserte Hautfestigkeit über Monate', 'Natürlich fortschreitende Wirkung'],
        goals_en: ['Stimulating the body\'s own collagen formation', 'Improved skin firmness over months', 'A naturally progressive effect'],
        duration_de: '30–45 Minuten', duration_en: '30–45 minutes',
      },
      {
        id: 'prp', subSlug: 'prp',
        title_de: 'PRP', title_en: 'PRP',
        lead_de: 'Aus einer kleinen Blutentnahme wird thrombozytenreiches Plasma gewonnen und in die Haut eingebracht, um Regeneration anzuregen.',
        lead_en: 'Platelet-rich plasma is obtained from a small blood draw and introduced into the skin to stimulate regeneration.',
        goals_de: ['Anregung körpereigener Regeneration', 'Verbesserte Hautqualität und Ausstrahlung', 'Gut geeignet zur Kombination mit anderen Verfahren'],
        goals_en: ['Stimulating the body\'s own regeneration', 'Improved skin quality and radiance', 'Well suited to combination with other procedures'],
        duration_de: '45 Minuten', duration_en: '45 minutes',
      },
      {
        id: 'microneedling', subSlug: 'microneedling',
        title_de: 'Microneedling', title_en: 'Microneedling',
        lead_de: 'Feinste Nadeln setzen gezielte Mikroverletzungen, die die Kollagen- und Elastinbildung der Haut anregen.',
        lead_en: 'Fine needles create controlled micro-injuries that stimulate the skin\'s collagen and elastin production.',
        goals_de: ['Feinere Hautstruktur und Poren', 'Verbesserte Aufnahme von Wirkstoffen', 'Milderung feiner Linien und Närbchen'],
        goals_en: ['A finer skin texture and reduced pore visibility', 'Improved absorption of active ingredients', 'Softening of fine lines and minor scarring'],
        duration_de: '30–45 Minuten', duration_en: '30–45 minutes',
      },
    ],
  },
};