// Standalone SEO subpages — Paket 3. Static content, medically plausible,
// pending final client approval (see AGENTS.md "Content Approval Status").
// Shape mirrors the Treatment entity; faqs use q_de/a_de + q_en/a_en pairs.
// Fact-grid fields (duration/downtime/results_onset/results_duration/price_from)
// and risks/contraindications have explicit _en variants so the English
// version never falls back to German medical/safety text.

import stirnfaltenEditorial from '@/assets/treatments/stirnfalten-editorial.jpg';
import zornesfalteEditorial from '@/assets/treatments/zornesfalte-editorial.jpg';
import jawlineMaleEditorial from '@/assets/treatments/jawline-male-portrait.jpg';
import schwitzenMaleEditorial from '@/assets/treatments/schwitzen-male-portrait.jpg';
import kinnMaleEditorial from '@/assets/treatments/kinn-male-portrait.jpg';

export const SUB_TREATMENTS = {
  stirnfalten: {
    slug: 'stirnfalten', category: 'botulinumtoxin', categoryPath: '/behandlungen/botulinumtoxin',
    title_de: 'Stirnfalten', title_en: 'Forehead Lines',
    meta_title_de: 'Stirnfalten behandeln | Faltenbehandlung Zürich | Aurea Aesthetics',
    meta_title_en: 'Forehead Line Smoothing | Wrinkle Treatment Zurich | Aurea Aesthetics',
    meta_description_de: 'Gezielte Glättung horizontaler Stirnfalten in Zürich — ärztlich durchgeführt, individuell dosiert, natürliche Mimik bleibt vollkommen erhalten.',
    meta_description_en: 'Targeted smoothing of horizontal forehead lines in Zurich — physician-led, individually dosed, natural expression preserved.',
    lead_de: 'Horizontale Fältchen auf der Stirn entstehen durch wiederholte Anspannung des Stirnmuskels. Eine präzise dosierte Behandlung glättet die Linien, ohne die Mimik zu erstarren.',
    lead_en: 'Horizontal forehead lines form through repeated tension of the frontalis muscle. A precisely dosed treatment smooths the lines without freezing expression.',
    image_url: stirnfaltenEditorial,
    indications: ['Horizontale Stirnfalten in Ruhe oder Bewegung', 'Müder oder angespannter Gesichtsausdruck', 'Vorbeugung tieferer Linien'],
    mechanism_de: 'Eine gezielte Entspannung des Musculus frontalis reduziert die übermässige Muskelspannung. Dadurch glättet sich die Haut über der Stirn sanft, während die Augenbrauenpartie natürlich beweglich bleibt.',
    mechanism_en: 'Targeted relaxation of the frontalis muscle reduces excessive muscle contraction, gently smoothing the forehead while preserving natural brow movement.',
    procedure_de: 'Nach genauer Analyse Ihrer Mimik und Muskelzüge erfolgen minimale Injektionen an definierten Punkten. Die Behandlung dauert ca. 15 bis 20 Minuten.',
    procedure_en: 'Following precise analysis of your expressions and muscle dynamics, minimal injections are placed at defined points. The procedure takes approximately 15 to 20 minutes.',
    duration: '15–20 Minuten', duration_en: '15–20 minutes',
    downtime: 'Keine', downtime_en: 'None',
    results_onset: '3–10 Tage', results_onset_en: '3–10 days',
    results_duration: '4–6 Monate', results_duration_en: '4–6 months',
    price_from: 'Auf Anfrage', price_from_en: 'On request',
    aftercare_de: 'Aufrechte Haltung für einige Stunden, keine Massage der Region, kein Sport oder Sauna am Behandlungstag.',
    aftercare_en: 'Remain upright for a few hours, avoid massaging the area, no sports or sauna on the day of treatment.',
    risks_de: 'Leichte Rötung, Schwellung oder kleine Blutergüsse an den Einstichstellen möglich. Selten vorübergehendes Absinken der Augenbraue.',
    risks_en: 'Possible temporary side effects include mild redness, swelling, or small bruises at the injection sites. Rarely, temporary brow drooping can occur.',
    contraindications_de: 'Nicht geeignet bei bestimmten neuromuskulären Erkrankungen, in der Schwangerschaft und Stillzeit sowie bei Infektionen im Behandlungsbereich.',
    contraindications_en: 'Not suitable for certain neuromuscular disorders, during pregnancy and breastfeeding, or in the presence of infections in the treatment area.',
    faqs: [
      { q_de: 'Wie schnell wirkt die Behandlung?', a_de: 'Erste Effekte zeigen sich meist nach 3 bis 5 Tagen, das volle Ergebnis nach etwa zwei Wochen.', q_en: 'How quickly does the treatment work?', a_en: 'Initial effects usually appear after 3 to 5 days, with the full result visible after about two weeks.' },
      { q_de: 'Sieht man, dass ich behandelt wurde?', a_de: 'Bei fachgerechter, individuell dosierter Anwendung bleibt die Mimik natürlich beweglich — ein "eingefrorener" Ausdruck ist nicht das Ziel.', q_en: 'Will it be visible that I was treated?', a_en: 'With expert, individually dosed application, expression remains naturally mobile — a "frozen" look is not the goal.' },
    ],
    medical_reviewer: 'Barbara Matziris',
  },
  zornesfalte: {
    slug: 'zornesfalte', category: 'botulinumtoxin', categoryPath: '/behandlungen/botulinumtoxin',
    title_de: 'Zornesfalte', title_en: 'Glabellar Frown Line',
    meta_title_de: 'Zornesfalte behandeln | Faltenbehandlung Zürich | Aurea Aesthetics',
    meta_title_en: 'Frown Line Treatment | Wrinkle Treatment Zurich | Aurea Aesthetics',
    meta_description_de: 'Behandlung der Zornesfalte zwischen den Augenbrauen in Zürich — für einen entspannteren, frischen und offenen Gesichtsausdruck.',
    meta_description_en: 'Targeted treatment of the glabellar frown line in Zurich — for a relaxed, refreshed, and open facial expression.',
    lead_de: 'Die senkrechte Falte zwischen den Augenbrauen kann einen unbeabsichtigt ernsten oder erschöpften Ausdruck erzeugen. Eine gezielte Behandlung löst die Spannung und öffnet den Blick.',
    lead_en: 'The vertical line between the brows can create an unintentionally stern or tired expression. Targeted treatment releases the tension and opens the gaze.',
    image_url: zornesfalteEditorial,
    indications: ['Ausgeprägte senkrechte Falte zwischen den Augenbrauen', 'Strenger oder erschöpft wirkender Ausdruck', 'Wunsch nach präventiver Behandlung'],
    mechanism_de: 'Durch die präzise Entlastung der Musculi corrugator supercilii und procerus wird die übermässige Spannung zwischen den Augenbrauen gelöst. Die senkrechte Falte glättet sich sichtbar.',
    mechanism_en: 'Targeted relaxation of the corrugator supercilii and procerus muscles eases tension between the brows, visibly smoothing the vertical line.',
    procedure_de: 'Nach Analyse der individuellen Muskelaktivität erfolgt die Injektion an mehreren definierten Punkten zwischen und über den Augenbrauen. Die Behandlung dauert 15 bis 20 Minuten.',
    procedure_en: 'Following analysis of individual muscle activity, injections are placed at several defined points between and above the brows. The treatment takes 15 to 20 minutes.',
    duration: '15–20 Minuten', duration_en: '15–20 minutes',
    downtime: 'Keine', downtime_en: 'None',
    results_onset: '3–10 Tage', results_onset_en: '3–10 days',
    results_duration: '4–6 Monate', results_duration_en: '4–6 months',
    price_from: 'Auf Anfrage', price_from_en: 'On request',
    aftercare_de: 'Aufrechte Haltung für einige Stunden, keine Massage der Region, kein Sport oder Sauna am Behandlungstag.',
    aftercare_en: 'Remain upright for several hours, no massage of the area, no exercise or sauna on the day of treatment.',
    risks_de: 'Leichte Rötung, Schwellung oder Bluterguss an den Einstichstellen möglich. Selten vorübergehendes Hängen des Augenlids.',
    risks_en: 'Mild redness, swelling, or bruising at the injection sites is possible. Rarely, temporary eyelid drooping.',
    contraindications_de: 'Nicht geeignet bei bestimmten neuromuskulären Erkrankungen, in Schwangerschaft und Stillzeit sowie bei Infektionen im Behandlungsbereich.',
    contraindications_en: 'Not suitable for certain neuromuscular disorders, during pregnancy and breastfeeding, or in the presence of infections in the treatment area.',
    faqs: [
      { q_de: 'Verändert die Behandlung meinen Blick?', a_de: 'Richtig platziert wirkt der Blick entspannter und offener — die natürliche Augenbrauenform bleibt erhalten.', q_en: 'Will the treatment change my expression?', a_en: 'Properly placed, your gaze appears more relaxed and open — your natural brow shape is preserved.' },
    ],
    medical_reviewer: 'Barbara Matziris',
  },
  kraehenfuesse: {
    slug: 'kraehenfuesse', category: 'botulinumtoxin', categoryPath: '/behandlungen/botulinumtoxin',
    title_de: 'Krähenfüsse', title_en: 'Crow\'s Feet',
    meta_title_de: 'Krähenfüsse glätten | Faltenbehandlung Zürich | Aurea Aesthetics',
    meta_title_en: 'Crow\'s Feet Smoothing | Wrinkle Treatment Zurich | Aurea Aesthetics',
    meta_description_de: 'Sanfte Glättung von Lachfältchen am äusseren Augenwinkel in Zürich — für einen wachen, erholten Blick bei voll erhaltenem Lächeln.',
    meta_description_en: 'Gentle smoothing of laugh lines at the outer eye corner in Zurich — for a refreshed look while preserving your natural smile.',
    lead_de: 'Feine Fältchen am äusseren Augenwinkel entstehen durch wiederholtes Lachen und Blinzeln. Eine behutsame Behandlung öffnet den Blick, ohne dem Lachen seine Lebendigkeit zu nehmen.',
    lead_en: 'Fine lines at the outer corners of the eyes result from smiling and squinting. Gentle treatment opens the gaze without diminishing the vitality of your smile.',
    image_url: 'https://media.base44.com/images/public/6a6b131f6cc49b3ee60e929e/9147ba321_generated_image.png',
    indications: ['Strahlende Lachfalten am Augenwinkel in Ruhe', 'Müde wirkende Augenpartie', 'Prävention tieferer Linien'],
    mechanism_de: 'Der äussere Teil des Musculus orbicularis oculi wird gezielt entspannt, wodurch sich die Haut beim Lachen weniger stark in Falten legt.',
    mechanism_en: 'The lateral part of the orbicularis oculi muscle is selectively relaxed, reducing crease formation when smiling.',
    procedure_de: 'Sehr feine Injektionen an wenigen Punkten lateral des Auges. Die Behandlung dauert etwa 15 Minuten.',
    procedure_en: 'Very fine injections at a few points lateral to the eye. The treatment takes about 15 minutes.',
    duration: '15 Minuten', duration_en: '15 minutes',
    downtime: 'Keine', downtime_en: 'None',
    results_onset: '3–7 Tage', results_onset_en: '3–7 days',
    results_duration: '3–5 Monate', results_duration_en: '3–5 months',
    price_from: 'Auf Anfrage', price_from_en: 'On request',
    aftercare_de: 'Kein Reiben der Augenpartie in den ersten Stunden, kein Sport oder Sauna am Behandlungstag.',
    aftercare_en: 'Avoid rubbing the eye area for the first few hours, no exercise or sauna on the day of treatment.',
    risks_de: 'Leichte Rötung oder kleine Blutergüsse möglich. Bei zu naher Injektion selten Schwellung des Unterlids.',
    risks_en: 'Mild redness or small bruises are possible. Rarely, under-eye swelling if injected too closely.',
    contraindications_de: 'Nicht geeignet bei bestimmten neuromuskulären Erkrankungen, in Schwangerschaft und Stillzeit sowie bei Infektionen im Behandlungsbereich.',
    contraindications_en: 'Not suitable for certain neuromuscular disorders, during pregnancy and breastfeeding, or in the presence of infections in the treatment area.',
    faqs: [
      { q_de: 'Kann ich danach noch natürlich lachen?', a_de: 'Ja. Die Dosierung wird so gewählt, dass die Augenpartie beim Lachen lebendig bleibt und lediglich die Tiefe der Falten gemildert wird.', q_en: 'Will I still be able to smile naturally?', a_en: 'Yes. Dosing is chosen so that the eye area remains lively when smiling, merely softening the depth of lines.' },
    ],
    medical_reviewer: 'Barbara Matziris',
  },
  'masseter-zaehneknirschen': {
    slug: 'masseter-zaehneknirschen', category: 'botulinumtoxin', categoryPath: '/behandlungen/botulinumtoxin',
    title_de: 'Masseter und Zähneknirschen', title_en: 'Masseter & Teeth Grinding',
    meta_title_de: 'Masseter-Behandlung & Zähneknirschen | Zürich | Aurea Aesthetics',
    meta_title_en: 'Masseter Treatment & Teeth Grinding | Zurich | Aurea Aesthetics',
    meta_description_de: 'Behandlung des Kaumuskels bei Zähneknirschen und Kieferverspannung in Zürich — für spürbare Entlastung und eine harmonische Kieferkontur.',
    meta_description_en: 'Masseter muscle treatment for teeth grinding and jaw tension in Zurich — for relief and a refined jawline contour.',
    lead_de: 'Eine Überaktivität des Kaumuskels führt häufig zu nächtlichem Zähneknirschen, Kieferverspannung und Kopfschmerzen — und kann zusätzlich zu einer breiteren Unterkieferkontur führen.',
    lead_en: 'Overactivity of the masseter muscle often causes nighttime teeth grinding, jaw tension, and headaches — and can also widen the lower-jaw contour.',
    image_url: 'https://media.base44.com/images/public/6a6b131f6cc49b3ee60e929e/9147ba321_generated_image.png',
    indications: ['Nächtliches Zähneknirschen (Bruxismus)', 'Kieferverspannung und begleitende Kopfschmerzen', 'Wunsch nach schlankerer Unterkieferkontur'],
    mechanism_de: 'Die gezielte Entspannung des Musculus masseter reduziert dessen Überaktivität. Dies entlastet das Kiefergelenk, lindert Verspannungen und kann zu einer harmonischeren Unterkieferkontur führen.',
    mechanism_en: 'Targeted relaxation of the masseter muscle reduces hypertonicity, relieving jaw tension and refining the lower-jaw contour.',
    procedure_de: 'Nach Tastbefund des Muskels bei Anspannung erfolgt die Injektion beidseitig in mehreren Punkten. Die Behandlung dauert 20 bis 30 Minuten.',
    procedure_en: 'After palpating the muscle under tension, injections are placed at several points on both sides. The treatment takes 20 to 30 minutes.',
    duration: '20–30 Minuten', duration_en: '20–30 minutes',
    downtime: 'Keine', downtime_en: 'None',
    results_onset: '1–3 Wochen', results_onset_en: '1–3 weeks',
    results_duration: '4–6 Monate', results_duration_en: '4–6 months',
    price_from: 'Auf Anfrage', price_from_en: 'On request',
    aftercare_de: 'Vermeiden Sie starkes Kauen (z. B. Kaugummi) in den ersten Tagen. Leichte Druckempfindlichkeit im Kaumuskel ist normal.',
    aftercare_en: 'Avoid vigorous chewing (e.g. gum) for the first few days. Mild tenderness in the masseter muscle is normal.',
    risks_de: 'Vorübergehende Kauschwäche bei zu hoher Dosierung möglich, daher schrittweise, individuelle Dosierung. Leichte Schwellung oder Bluterguss möglich.',
    risks_en: 'Temporary chewing weakness is possible if dosed too high, which is why dosing is stepwise and individualised. Mild swelling or bruising is possible.',
    contraindications_de: 'Nicht geeignet bei bestimmten neuromuskulären Erkrankungen, in Schwangerschaft und Stillzeit sowie bei bestehenden Kaumuskelerkrankungen ohne vorherige Abklärung.',
    contraindications_en: 'Not suitable for certain neuromuscular disorders, during pregnancy and breastfeeding, or for existing masseter muscle conditions without prior assessment.',
    faqs: [
      { q_de: 'Wie lange dauert es, bis sich der Kiefer schlanker zeigt?', a_de: 'Die konturierende Wirkung zeigt sich meist nach 4 bis 8 Wochen, da sich der Muskel über diese Zeit zurückbildet.', q_en: 'How long until the jaw appears slimmer?', a_en: 'The contouring effect usually becomes visible after 4 to 8 weeks, as the muscle gradually reduces in size.' },
      { q_de: 'Hilft die Behandlung wirklich gegen Knirschen?', a_de: 'Viele Patientinnen und Patienten berichten von deutlich weniger nächtlichem Knirschen und Verspannung. Bei ausgeprägtem Bruxismus empfehlen wir zusätzlich eine zahnärztliche Abklärung.', q_en: 'Does the treatment really help with grinding?', a_en: 'Many patients report significantly less nighttime grinding and tension. For pronounced bruxism, we also recommend a dental evaluation.' },
    ],
    medical_reviewer: 'Nadine Dovi-Akue',
  },
  schwitzen: {
    slug: 'schwitzen', category: 'botulinumtoxin', categoryPath: '/behandlungen/botulinumtoxin',
    title_de: 'Übermässiges Schwitzen', title_en: 'Excessive Sweating',
    meta_title_de: 'Behandlung bei übermässigem Schwitzen | Zürich | Aurea Aesthetics',
    meta_title_en: 'Excessive Sweating Treatment | Zurich | Aurea Aesthetics',
    meta_description_de: 'Behandlung der Hyperhidrose in Achseln, Händen oder Füssen in Zürich — effektive Reduktion der übermässigen Schweissproduktion über Monate.',
    meta_description_en: 'Hyperhidrosis treatment for underarms, hands, or feet in Zurich — effective reduction of excessive sweat production for months.',
    lead_de: 'Übermässiges Schwitzen (Hyperhidrose) kann den Alltag deutlich einschränken. Eine gezielte Behandlung reduziert die Aktivität der Schweissdrüsen spürbar und über Monate.',
    lead_en: 'Excessive sweating (hyperhidrosis) can significantly limit daily life. Targeted treatment noticeably reduces sweat gland activity for months.',
    image_url: schwitzenMaleEditorial,
    indications: ['Übermässiges Schwitzen in den Achseln', 'Übermässiges Schwitzen an Händen oder Füssen', 'Alltägliche Einschränkung durch Hyperhidrose'],
    mechanism_de: 'Die gezielte Blockade überaktiver Nervenimpulse an den Schweissdrüsen normalisiert die Schweissproduktion in der behandelten Region spürbar und lang anhaltend.',
    mechanism_en: 'Targeted modulation of nerve signals to the sweat glands significantly normalizes local perspiration for many months.',
    procedure_de: 'Nach Bestimmung der betroffenen Fläche (ggf. mittels Jod-Stärke-Test) erfolgen zahlreiche kleine, oberflächliche Injektionen im gesamten Areal. Die Behandlung dauert 30 bis 45 Minuten.',
    procedure_en: 'After determining the affected area (optionally using an iodine-starch test), numerous small, superficial injections are placed across the entire region. The treatment takes 30 to 45 minutes.',
    duration: '30–45 Minuten', duration_en: '30–45 minutes',
    downtime: 'Keine', downtime_en: 'None',
    results_onset: '1–2 Wochen', results_onset_en: '1–2 weeks',
    results_duration: '6–9 Monate', results_duration_en: '6–9 months',
    price_from: 'Auf Anfrage', price_from_en: 'On request',
    aftercare_de: 'Keine besonderen Einschränkungen. Sport und Sauna sollten am Behandlungstag vermieden werden.',
    aftercare_en: 'No particular restrictions. Exercise and sauna should be avoided on the day of treatment.',
    risks_de: 'Leichte Rötung oder Druckempfindlichkeit an den Einstichstellen möglich. Bei Handbehandlung selten vorübergehende Griffkraftminderung.',
    risks_en: 'Mild redness or tenderness at the injection sites is possible. For hand treatment, rarely a temporary reduction in grip strength.',
    contraindications_de: 'Nicht geeignet bei bestimmten neuromuskulären Erkrankungen, in Schwangerschaft und Stillzeit sowie bei Infektionen im Behandlungsbereich.',
    contraindications_en: 'Not suitable for certain neuromuscular disorders, during pregnancy and breastfeeding, or in the presence of infections in the treatment area.',
    faqs: [
      { q_de: 'Wie lange hält die Wirkung an?', a_de: 'Die Wirkung hält je nach Körperregion in der Regel 6 bis 9 Monate an, an den Achseln oft am längsten.', q_en: 'How long does the effect last?', a_en: 'Depending on the body region, the effect typically lasts 6 to 9 months, often longest in the underarms.' },
    ],
    medical_reviewer: 'Nadine Dovi-Akue',
  },
  lippenbehandlung: {
    slug: 'lippenbehandlung', category: 'hyaluron-konturierung', categoryPath: '/behandlungen/hyaluron-konturierung',
    title_de: 'Lippenbehandlung', title_en: 'Lip Treatment',
    meta_title_de: 'Lippenbehandlung mit Hyaluronsäure | Zürich | Aurea Aesthetics',
    meta_title_en: 'Lip Treatment with Hyaluronic Acid | Zurich | Aurea Aesthetics',
    meta_description_de: 'Natürliche Lippenkonturierung mit Hyaluronsäure in Zürich — individuell abgestimmt auf Ihre Gesichtsproportionen.',
    meta_description_en: 'Natural lip contouring with hyaluronic acid in Zurich — individually tailored to your facial proportions.',
    lead_de: 'Feine Konturierung und dezenter Volumenaufbau lassen die Lippen ausgewogen wirken, ohne die individuelle Anatomie zu überschreiben.',
    lead_en: 'Fine contouring and subtle volume enhancement create balanced lips without overriding individual anatomy.',
    image_url: 'https://media.base44.com/images/public/6a6b131f6cc49b3ee60e929e/aa2efde7c_generated_image.png',
    indications: ['Wunsch nach mehr Lippenvolumen', 'Ausgleich von Asymmetrien', 'Auffüllen feiner Fältchen um den Mund'],
    mechanism_de: 'Hyaluronsäure wird fein dosiert in die Lippen eingebracht, um Kontur und Volumen gezielt zu formen. Die Substanz bindet zusätzlich Feuchtigkeit im Gewebe.',
    mechanism_en: 'Hyaluronic acid is finely dosed into the lips to shape contour and volume. The substance also binds moisture within the tissue.',
    procedure_de: 'Nach Analyse der Lippenform und Absprache Ihrer Wünsche erfolgt die Injektion mit feinsten Kanülen. Eine betäubende Creme kann vorab aufgetragen werden. Die Behandlung dauert etwa 30 Minuten.',
    procedure_en: 'After analysing lip shape and discussing your wishes, the treatment is administered using the finest cannulas. A numbing cream may be applied beforehand. The treatment takes about 30 minutes.',
    duration: '30 Minuten', duration_en: '30 minutes',
    downtime: '1–3 Tage leichte Schwellung', downtime_en: '1–3 days mild swelling',
    results_onset: 'Sofort', results_onset_en: 'Immediate',
    results_duration: '6–12 Monate', results_duration_en: '6–12 months',
    price_from: 'Auf Anfrage', price_from_en: 'On request',
    aftercare_de: 'Leichte Schwellung in den ersten Tagen ist normal. Vermeiden Sie in den ersten 48 Stunden starke Hitze, Sport und Alkohol.',
    aftercare_en: 'Mild swelling in the first few days is normal. Avoid intense heat, exercise, and alcohol for the first 48 hours.',
    risks_de: 'Schwellung, Rötung oder kleine Blutergüsse sind häufig und klingen innerhalb weniger Tage ab. Selten Knötchenbildung.',
    risks_en: 'Swelling, redness, or small bruises are common and subside within a few days. Rarely, small nodules.',
    contraindications_de: 'Nicht geeignet bei akuten Infektionen im Mundbereich, in der Schwangerschaft und Stillzeit sowie bei bekannter Hyaluronsäure-Unverträglichkeit.',
    contraindications_en: 'Not suitable for acute infections in the mouth area, during pregnancy and breastfeeding, or with known hyaluronic acid intolerance.',
    faqs: [
      { q_de: 'Wirken die Lippen danach künstlich?', a_de: 'Ziel ist ein ausgewogenes, der eigenen Anatomie entsprechendes Ergebnis. Wir arbeiten mit zurückhaltender Dosierung und bauen Volumen bei Bedarf über mehrere Sitzungen auf.', q_en: 'Will the lips look artificial afterwards?', a_en: 'The goal is a balanced result that suits your own anatomy. We work with restrained dosing and build volume gradually over multiple sessions if needed.' },
    ],
    medical_reviewer: 'Barbara Matziris',
  },
  jawline: {
    slug: 'jawline', category: 'hyaluron-konturierung', categoryPath: '/behandlungen/hyaluron-konturierung',
    title_de: 'Jawline', title_en: 'Jawline',
    meta_title_de: 'Jawline-Konturierung mit Hyaluronsäure | Zürich | Aurea Aesthetics',
    meta_title_en: 'Jawline Contouring with Hyaluronic Acid | Zurich | Aurea Aesthetics',
    meta_description_de: 'Definierte Kieferlinie durch Hyaluronsäure-Konturierung in Zürich — individuell geplant für ein klareres Profil.',
    meta_description_en: 'A defined jawline through hyaluronic acid contouring in Zurich — individually planned for a clearer profile.',
    lead_de: 'Eine gezielte Konturierung entlang des Unterkiefers definiert die Gesichtslinie und schafft ein klareres, gestrafftes Profil.',
    lead_en: 'Targeted contouring along the lower jaw defines the facial line and creates a clearer, more sculpted profile.',
    image_url: jawlineMaleEditorial,
    indications: ['Wunsch nach klarerer Kieferlinie', 'Ausgleich einer weichen Unterkieferkontur', 'Verbesserung des seitlichen Profils'],
    mechanism_de: 'Hyaluronsäure wird entlang des Unterkieferknochens platziert, um die Kontur zu stützen und zu definieren, ohne das Gesicht zu verbreitern.',
    mechanism_en: 'Hyaluronic acid is placed along the jawbone to support and define the contour without widening the face.',
    procedure_de: 'Nach Analyse des Profils in Ruhe und Bewegung erfolgt die Injektion entlang der Kieferlinie mit Kanüle oder feiner Nadel. Die Behandlung dauert 30 bis 45 Minuten.',
    procedure_en: 'After analysing the profile at rest and in motion, injections are placed along the jawline using a cannula or fine needle. The treatment takes 30 to 45 minutes.',
    duration: '30–45 Minuten', duration_en: '30–45 minutes',
    downtime: '2–4 Tage leichte Schwellung', downtime_en: '2–4 days mild swelling',
    results_onset: 'Sofort, endgültig nach 2 Wochen', results_onset_en: 'Immediate, final after 2 weeks',
    results_duration: '9–14 Monate', results_duration_en: '9–14 months',
    price_from: 'Auf Anfrage', price_from_en: 'On request',
    aftercare_de: 'Leichte Schwellung und Druckempfindlichkeit sind in den ersten Tagen normal. Vermeiden Sie starke Hitze und intensiven Sport für 48 Stunden.',
    aftercare_en: 'Mild swelling and tenderness are normal for the first few days. Avoid intense heat and vigorous exercise for 48 hours.',
    risks_de: 'Schwellung, Rötung oder Blutergüsse möglich. Selten Asymmetrien, die nachkorrigiert werden können.',
    risks_en: 'Swelling, redness, or bruising is possible. Rarely, asymmetries that can be corrected in a follow-up.',
    contraindications_de: 'Nicht geeignet bei akuten Infektionen im Behandlungsbereich, in Schwangerschaft und Stillzeit sowie bei bekannter Hyaluronsäure-Unverträglichkeit.',
    contraindications_en: 'Not suitable for acute infections in the treatment area, during pregnancy and breastfeeding, or with known hyaluronic acid intolerance.',
    faqs: [
      { q_de: 'Wird das Gesicht dadurch breiter?', a_de: 'Bei fachgerechter Platzierung entlang des Knochens wirkt die Kieferlinie definierter, nicht breiter — die Konturierung folgt der individuellen Anatomie.', q_en: 'Will this make the face wider?', a_en: 'With expert placement along the bone, the jawline appears more defined, not wider — contouring follows individual anatomy.' },
    ],
    medical_reviewer: 'Nadine Dovi-Akue',
  },
  prp: {
    slug: 'prp', category: 'hautqualitaet-regeneration', categoryPath: '/behandlungen/hautqualitaet-regeneration',
    title_de: 'PRP', title_en: 'PRP',
    meta_title_de: 'PRP-Behandlung (Eigenblut) | Zürich | Aurea Aesthetics',
    meta_title_en: 'PRP Treatment (Platelet-Rich Plasma) | Zurich | Aurea Aesthetics',
    meta_description_de: 'PRP-Behandlung mit körpereigenem, thrombozytenreichem Plasma in Zürich — zur Anregung der Hautregeneration.',
    meta_description_en: 'PRP treatment with the body\'s own platelet-rich plasma in Zurich — to stimulate skin regeneration.',
    lead_de: 'Aus einer kleinen Blutentnahme wird thrombozytenreiches Plasma gewonnen und gezielt in die Haut eingebracht, um körpereigene Regenerationsprozesse anzuregen.',
    lead_en: 'Platelet-rich plasma is obtained from a small blood draw and introduced into the skin to stimulate the body\'s own regeneration processes.',
    image_url: 'https://media.base44.com/images/public/6a6b131f6cc49b3ee60e929e/178c12a52_generated_image.png',
    indications: ['Müde, fahle Hautqualität', 'Feine Linien und verminderte Elastizität', 'Wunsch nach einem rein körpereigenen Verfahren'],
    mechanism_de: 'Aus einer kleinen Blutprobe wird in einer Zentrifuge das thrombozytenreiche Plasma isoliert. Die enthaltenen Wachstumsfaktoren regen bei Injektion in die Haut die körpereigene Kollagen- und Zellregeneration an.',
    mechanism_en: 'From a small blood sample, platelet-rich plasma is isolated using a centrifuge. When injected into the skin, the growth factors it contains stimulate the body\'s own collagen and cell regeneration.',
    procedure_de: 'Nach einer kleinen Blutentnahme wird das Plasma aufbereitet und anschliessend mit feinen Nadeln in die Haut eingebracht. Die Behandlung dauert etwa 45 Minuten.',
    procedure_en: 'After a small blood draw, the plasma is processed and then introduced into the skin using fine needles. The treatment takes about 45 minutes.',
    duration: '45 Minuten', duration_en: '45 minutes',
    downtime: '1–2 Tage leichte Rötung', downtime_en: '1–2 days mild redness',
    results_onset: 'Nach mehreren Wochen', results_onset_en: 'After several weeks',
    results_duration: '6–9 Monate', results_duration_en: '6–9 months',
    price_from: 'Auf Anfrage', price_from_en: 'On request',
    aftercare_de: 'Leichte Rötung und Schwellung sind in den ersten Tagen normal. Direkte Sonneneinstrahlung und Sauna sollten für einige Tage vermieden werden.',
    aftercare_en: 'Mild redness and swelling are normal for the first few days. Avoid direct sun exposure and sauna for several days.',
    risks_de: 'Rötung, Schwellung oder kleine Blutergüsse an den Einstichstellen möglich. Da körpereigenes Material verwendet wird, ist das allergische Risiko sehr gering.',
    risks_en: 'Redness, swelling, or small bruises at the injection sites are possible. Since the body\'s own material is used, allergic risk is very low.',
    contraindications_de: 'Nicht geeignet bei bestimmten Blutgerinnungsstörungen, akuten Infektionen sowie in bestimmten Blutbild-Konstellationen — Abklärung im Beratungsgespräch.',
    contraindications_en: 'Not suitable for certain blood clotting disorders, acute infections, or specific blood count conditions — assessed during consultation.',
    faqs: [
      { q_de: 'Ist PRP ein rein natürliches Verfahren?', a_de: 'Ja, es wird ausschliesslich körpereigenes Material verwendet — es kommen keine Fremdsubstanzen zum Einsatz.', q_en: 'Is PRP a fully natural procedure?', a_en: 'Yes, only your own body\'s material is used — no foreign substances are involved.' },
    ],
    medical_reviewer: 'Barbara Matziris',
  },
  microneedling: {
    slug: 'microneedling', category: 'hautqualitaet-regeneration', categoryPath: '/behandlungen/hautqualitaet-regeneration',
    title_de: 'Microneedling', title_en: 'Microneedling',
    meta_title_de: 'Microneedling-Behandlung | Zürich | Aurea Aesthetics',
    meta_title_en: 'Microneedling Treatment | Zurich | Aurea Aesthetics',
    meta_description_de: 'Microneedling in Zürich zur Verfeinerung der Hautstruktur — regt Kollagenbildung an und verbessert die Wirkstoffaufnahme.',
    meta_description_en: 'Microneedling in Zurich to refine skin texture — stimulates collagen formation and improves active-ingredient absorption.',
    lead_de: 'Feinste Nadeln setzen gezielte Mikroverletzungen in der Haut, die körpereigene Reparaturprozesse und die Kollagenbildung anregen.',
    lead_en: 'Fine needles create controlled micro-injuries in the skin that stimulate the body\'s own repair processes and collagen formation.',
    image_url: 'https://media.base44.com/images/public/6a6b131f6cc49b3ee60e929e/178c12a52_generated_image.png',
    indications: ['Grobporige oder unebene Hautstruktur', 'Feine Linien und leichte Närbchen', 'Wunsch nach verbesserter Wirkstoffaufnahme'],
    mechanism_de: 'Ein medizinisches Needling-Gerät setzt feinste, kontrollierte Mikroverletzungen in der obersten Hautschicht. Dies löst einen natürlichen Heilungsprozess aus, der die Kollagen- und Elastinbildung anregt.',
    mechanism_en: 'A medical needling device creates fine, controlled micro-injuries in the uppermost skin layer. This triggers a natural healing process that stimulates collagen and elastin production.',
    procedure_de: 'Nach Reinigung der Haut und Auftragen einer betäubenden Creme wird die Behandlung flächig über das Gesicht durchgeführt. Die Behandlung dauert 30 bis 45 Minuten.',
    procedure_en: 'After cleansing the skin and applying a numbing cream, the treatment is performed across the face. The treatment takes 30 to 45 minutes.',
    duration: '30–45 Minuten', duration_en: '30–45 minutes',
    downtime: '1–3 Tage Rötung', downtime_en: '1–3 days redness',
    results_onset: 'Nach mehreren Wochen', results_onset_en: 'After several weeks',
    results_duration: 'Kumulativ über mehrere Sitzungen', results_duration_en: 'Cumulative over several sessions',
    price_from: 'Auf Anfrage', price_from_en: 'On request',
    aftercare_de: 'Die Haut zeigt sich in den ersten Tagen gerötet, ähnlich einem leichten Sonnenbrand. Sonnenschutz ist in den folgenden Tagen besonders wichtig.',
    aftercare_en: 'The skin appears red for the first few days, similar to mild sunburn. Sun protection is especially important in the following days.',
    risks_de: 'Rötung, leichte Schwellung und Spannungsgefühl sind häufig und klingen innerhalb weniger Tage ab. Selten Pigmentveränderungen.',
    risks_en: 'Redness, mild swelling, and a feeling of tightness are common and subside within a few days. Rarely, pigmentation changes.',
    contraindications_de: 'Nicht geeignet bei aktiven Hautinfektionen, Ekzemen im Behandlungsbereich, in der Schwangerschaft ohne vorherige Abklärung sowie bei Neigung zu Keloidbildung.',
    contraindications_en: 'Not suitable for active skin infections, eczema in the treatment area, pregnancy without prior assessment, or a tendency toward keloid formation.',
    faqs: [
      { q_de: 'Wie viele Sitzungen sind empfehlenswert?', a_de: 'Für ein sichtbares Ergebnis empfehlen wir in der Regel eine Serie von 3 bis 4 Sitzungen im Abstand von 4 bis 6 Wochen.', q_en: 'How many sessions are recommended?', a_en: 'For a visible result, we generally recommend a series of 3 to 4 sessions spaced 4 to 6 weeks apart.' },
    ],
    medical_reviewer: 'Nadine Dovi-Akue',
  },
  'hyaluron-aufloesen-hylase': {
    slug: 'hyaluron-aufloesen-hylase', category: 'hyaluron-konturierung', categoryPath: '/behandlungen/hyaluron-konturierung',
    title_de: 'Hyaluron auflösen mit Hylase', title_en: 'Dissolving Hyaluronic Acid with Hylase',
    meta_title_de: 'Hyaluron auflösen mit Hylase | Hyaluronidase Korrektur Zürich | Aurea Aesthetics',
    meta_title_en: 'Dissolving Hyaluronic Acid with Hylase | Hyaluronidase Zurich | Aurea Aesthetics',
    meta_description_de: 'Präzises Auflösen und Korrigieren von Hyaluron-Fillern mit Hylase (Hyaluronidase) in Zürich — bei Knötchen, Asymmetrien oder zur Vorbereitung auf einen Lippen-Neuaufbau.',
    meta_description_en: 'Targeted correction and dissolving of hyaluronic acid fillers with Hylase (hyaluronidase) in Zurich — for nodules, asymmetries, or preparing for fresh lip reconstruction.',
    lead_de: 'Nicht jedes Hyaluron-Ergebnis erfüllt die eigenen Vorstellungen. Mit dem Enzym Hyaluronidase (Hylase) können unerwünschte Depots, Asymmetrien oder Knötchen präzise und schonend aufgelöst werden — auch als optimale Basis für einen anschliessenden harmonischen Neuaufbau.',
    lead_en: 'Not every hyaluronic acid treatment yields the desired outcome. With the enzyme hyaluronidase (Hylase), unwanted filler deposits, asymmetries, or nodules can be dissolved with precision — creating an ideal foundation for fresh, harmonious contouring.',
    image_url: 'https://media.base44.com/images/public/6a6b131f6cc49b3ee60e929e/aa2efde7c_generated_image.png',
    indications: [
      'Unerwünschte Filler-Ergebnisse oder Überkorrekturen nach Vorbehandlungen',
      'Tastbare Knötchen, Unebenheiten oder sichtbare Wülste',
      'Verrutschtes Hyaluron (Migration, z. B. oberhalb des Lippenrands)',
      'Tyndall-Effekt (bläulicher Schimmer durch oberflächlich platziertes Material)',
      'Gezielte Vorbereitung auf einen neuen, anatomisch stimmigen Lippenaufbau'
    ],
    mechanism_de: 'Hyaluronidase ist ein hochwirksames Enzym, das die Quervernetzungen synthetischer Hyaluronsäure spaltet. Das eingebrachte Material wird innerhalb kurzer Zeit in natürliche Bestandteile zerlegt und vom Körper resorbiert, sodass das Gewebe in seinen entspannten Ausgangszustand zurückkehrt.',
    mechanism_en: 'Hyaluronidase is an enzyme that selectively breaks down the cross-links of synthetic hyaluronic acid. The filler material is quickly metabolised and naturally cleared by the body, allowing the tissue to return to its original state.',
    procedure_de: 'Nach eingehender Untersuchung, exakter Lokalisierung der Depots und individueller Dosierungsplanung wird Hylase mit mikrofeinen Nadeln punktgenau injiziert. Die Behandlung dauert ca. 20 bis 30 Minuten und kann auf Wunsch mit einer lokalen Anästhesiecreme kombiniert werden.',
    procedure_en: 'Following detailed assessment, precise localization of filler deposits, and tailored dosage planning, Hylase is injected with micro-fine needles. The procedure takes 20 to 30 minutes and can be combined with a topical numbing cream.',
    duration: '20–30 Minuten', duration_en: '20–30 minutes',
    downtime: '1–2 Tage leichte Schwellung / Rötung', downtime_en: '1–2 days mild swelling / redness',
    results_onset: 'Erste Wirkung nach wenigen Stunden, Endresultat nach 3–7 Tagen', results_onset_en: 'Initial effect within hours, full resolution after 3–7 days',
    results_duration: 'Dauerhaft aufgelöst', results_duration_en: 'Permanently dissolved',
    price_from: 'Auf Anfrage', price_from_en: 'On request',
    aftercare_de: 'Leichte Schwellung oder Rötung in den ersten 24 Stunden sanft kühlen. Für 48 Stunden intensive Hitze, Sport und Sauna meiden. Ein neuer Hyaluron-Aufbau (z. B. der Lippen) sollte frühestens nach 10 bis 14 Tagen erfolgen.',
    aftercare_en: 'Gently cool the area during the first 24 hours. Avoid intense heat, saunas, and strenuous exercise for 48 hours. Fresh hyaluronic acid enhancement (e.g. lip filling) should be scheduled at least 10–14 days later.',
    risks_de: 'Vorübergehende Schwellung, Rötung oder kleine Einstich-Hämatome sind normal. Allergische Reaktionen sind selten, werden aber durch eine gründliche Anamnese und ggf. Vorab-Testung minimiert.',
    risks_en: 'Temporary swelling, redness, or small bruises are typical and resolve quickly. Allergic reactions are rare and minimized through comprehensive medical screening.',
    contraindications_de: 'Bekannte Allergie gegen Hyaluronidase oder Bienen-/Wespengift, Schwangerschaft und Stillzeit sowie akute Entzündungen oder Infektionen im Behandlungsareal.',
    contraindications_en: 'Known allergy to hyaluronidase or bee/wasp venom, pregnancy and breastfeeding, or active infections in the treatment area.',
    faqs: [
      {
        q_de: 'Wann kann nach Hylase wieder neues Hyaluron aufgebaut werden?',
        a_de: 'Wir empfehlen ein Intervall von mindestens 10 bis 14 Tagen. Sobald das Gewebe vollständig abgeschwollen und das alte Material abgebaut ist, kann ein neuer, harmonischer und präzise dosierter Aufbau erfolgen.',
        q_en: 'When can new filler be injected after Hylase?',
        a_en: 'We recommend waiting at least 10 to 14 days. Once the tissue has completely settled and the old material is fully cleared, a fresh, natural contouring can be performed.'
      },
      {
        q_de: 'Wie schnell wirkt die Behandlung mit Hylase?',
        a_de: 'Das Enzym beginnt unmittelbar nach der Injektion zu arbeiten. Erste spürbare und sichtbare Veränderungen treten bereits nach wenigen Stunden ein, das endgültige Ergebnis ist nach etwa 3 bis 7 Tagen erreicht.',
        q_en: 'How quickly does Hylase take effect?',
        a_en: 'The enzyme begins working immediately upon injection. Noticeable changes occur within hours, with the final result visible after 3 to 7 days.'
      },
      {
        q_de: 'Greift Hylase mein eigenes Gewebe an?',
        a_de: 'Hylase spaltet vor allem das synthetisch vernetzte Hyaluron. Das körpereigene Hyaluron im Bindegewebe kann kurzzeitig minimal mitreagieren, wird vom Körper jedoch innerhalb weniger Tage vollständig selbstständig wieder aufgebaut.',
        q_en: 'Does Hylase damage natural tissue?',
        a_en: 'Hylase predominantly targets the cross-linked synthetic filler. While natural tissue hyaluronic acid may experience minor transient depletion, the body fully regenerates it within days.'
      }
    ],
    medical_reviewer: 'Barbara Matziris',
  },
};
