// Standalone SEO subpages — Paket 3. Static content, medically plausible,
// pending final client approval (see AGENTS.md "Content Approval Status").
// Shape mirrors the Treatment entity; faqs use q_de/a_de + q_en/a_en pairs.
// Fact-grid fields (duration/downtime/results_onset/results_duration/price_from)
// and risks/contraindications have explicit _en variants so the English
// version never falls back to German medical/safety text.

import stirnfaltenEditorial from '@/assets/treatments/stirnfalten-editorial.jpg';
import zornesfalteEditorial from '@/assets/treatments/zornesfalte-editorial.jpg';

export const SUB_TREATMENTS = {
  stirnfalten: {
    slug: 'stirnfalten', category: 'botulinumtoxin', categoryPath: '/behandlungen/botulinumtoxin',
    title_de: 'Stirnfalten', title_en: 'Forehead Lines',
    meta_title_de: 'Stirnfalten behandeln | Botulinumtoxin Zürich | Aurea Aesthetics',
    meta_title_en: 'Forehead Line Treatment | Botulinum Toxin Zurich | Aurea Aesthetics',
    meta_description_de: 'Behandlung horizontaler Stirnfalten mit Botulinumtoxin in Zürich — ärztlich durchgeführt, individuell dosiert, natürliche Mimik bleibt erhalten.',
    meta_description_en: 'Treatment of horizontal forehead lines with botulinum toxin in Zurich — physician-led, individually dosed, natural expression preserved.',
    lead_de: 'Horizontale Fältchen auf der Stirn entstehen durch wiederholte Anspannung des Stirnmuskels. Eine präzise dosierte Behandlung glättet die Linien, ohne die Mimik zu erstarren.',
    lead_en: 'Horizontal forehead lines form through repeated tension of the frontalis muscle. A precisely dosed treatment smooths the lines without freezing expression.',
    image_url: stirnfaltenEditorial,
    indications: ['Horizontale Stirnfalten in Ruhe oder bei Bewegung', 'Beginnende, noch dynamische Faltenbildung', 'Wunsch nach präventiver Behandlung'],
    mechanism_de: 'Botulinumtoxin blockiert vorübergehend die Signalübertragung zwischen Nerv und Muskel im Bereich des Musculus frontalis. Die überaktive Muskelanspannung, die die Falten erzeugt, wird reduziert, während die Haut sich glättet.',
    mechanism_en: 'Botulinum toxin temporarily blocks signal transmission between nerve and muscle in the frontalis area. The overactive muscle tension that creates the lines is reduced, allowing the skin to smooth.',
    procedure_de: 'Nach einer ausführlichen Anamnese und Analyse Ihrer Mimik wird die Substanz mit einer feinen Nadel in mehreren kleinen Mengen in den Stirnmuskel injiziert. Die Behandlung dauert 15 bis 20 Minuten und erfordert keine Betäubung.',
    procedure_en: 'Following a thorough history and analysis of your facial expression, the substance is injected in several small amounts into the frontalis muscle using a fine needle. The treatment takes 15 to 20 minutes and requires no anaesthesia.',
    duration: '15–20 Minuten', duration_en: '15–20 minutes',
    downtime: 'Keine', downtime_en: 'None',
    results_onset: '3–10 Tage', results_onset_en: '3–10 days',
    results_duration: '4–6 Monate', results_duration_en: '4–6 months',
    price_from: 'Auf Anfrage', price_from_en: 'On request',
    aftercare_de: 'Nach der Behandlung sollten Sie für einige Stunden aufrechte Körperhaltung bewahren und die behandelte Region nicht reiben oder massieren. Sport und Sauna sollten am Behandlungstag vermieden werden.',
    aftercare_en: 'After treatment, remain upright for several hours and avoid rubbing or massaging the treated area. Exercise and sauna should be avoided on the day of treatment.',
    risks_de: 'Mögliche vorübergehende Nebenwirkungen umfassen leichte Rötung, Schwellung oder kleine Blutergüsse an den Einstichstellen. Selten kann es zu einem vorübergehenden Hängen des Augenlids kommen.',
    risks_en: 'Possible temporary side effects include mild redness, swelling, or small bruises at the injection sites. Rarely, temporary eyelid drooping can occur.',
    contraindications_de: 'Nicht geeignet bei bestimmten neuromuskulären Erkrankungen, in der Schwangerschaft und Stillzeit sowie bei Infektionen im Behandlungsbereich.',
    contraindications_en: 'Not suitable for certain neuromuscular disorders, during pregnancy and breastfeeding, or in the presence of infections in the treatment area.',
    faqs: [
      { q_de: 'Wie schnell wirkt die Behandlung?', a_de: 'Erste Effekte zeigen sich meist nach 3 bis 5 Tagen, das volle Ergebnis nach etwa zwei Wochen.', q_en: 'How quickly does the treatment work?', a_en: 'Initial effects usually appear after 3 to 5 days, with the full result visible after about two weeks.' },
      { q_de: 'Sieht man, dass ich behandelt wurde?', a_de: 'Bei fachgerechter, individuell dosierter Anwendung bleibt die Mimik natürlich beweglich — ein "eingefrorener" Ausdruck ist nicht das Ziel.', q_en: 'Will it be visible that I was treated?', a_en: 'With expert, individually dosed application, expression remains naturally mobile — a "frozen" look is not the goal.' },
    ],
    medical_reviewer: 'Dr. med. Barbara Matziris',
  },
  zornesfalte: {
    slug: 'zornesfalte', category: 'botulinumtoxin', categoryPath: '/behandlungen/botulinumtoxin',
    title_de: 'Zornesfalte', title_en: 'Glabellar Frown Line',
    meta_title_de: 'Zornesfalte behandeln | Botulinumtoxin Zürich | Aurea Aesthetics',
    meta_title_en: 'Frown Line Treatment | Botulinum Toxin Zurich | Aurea Aesthetics',
    meta_description_de: 'Behandlung der Zornesfalte zwischen den Augenbrauen mit Botulinumtoxin in Zürich — für einen entspannteren, offeneren Ausdruck.',
    meta_description_en: 'Treatment of the glabellar frown line between the brows with botulinum toxin in Zurich — for a more relaxed, open expression.',
    lead_de: 'Die senkrechte Falte zwischen den Augenbrauen kann einen unbeabsichtigt ernsten oder erschöpften Ausdruck erzeugen. Eine gezielte Behandlung löst die Spannung und öffnet den Blick.',
    lead_en: 'The vertical line between the brows can create an unintentionally stern or tired expression. Targeted treatment releases the tension and opens the gaze.',
    image_url: zornesfalteEditorial,
    indications: ['Ausgeprägte senkrechte Falte zwischen den Augenbrauen', 'Strenger oder erschöpft wirkender Ausdruck', 'Wunsch nach präventiver Behandlung'],
    mechanism_de: 'Die Substanz wirkt auf die Musculi corrugator supercilii und procerus, die für das Zusammenziehen der Augenbrauen verantwortlich sind. Ihre Aktivität wird reduziert, wodurch sich die Falte glättet.',
    mechanism_en: 'The substance acts on the corrugator supercilii and procerus muscles, which are responsible for pulling the brows together. Their activity is reduced, smoothing the line.',
    procedure_de: 'Nach Analyse der individuellen Muskelaktivität erfolgt die Injektion an mehreren definierten Punkten zwischen und über den Augenbrauen. Die Behandlung dauert 15 bis 20 Minuten.',
    procedure_en: 'Following analysis of individual muscle activity, injections are placed at several defined points between and above the brows. The treatment takes 15 to 20 minutes.',
    duration: '15–20 Minuten', duration_en: '15–20 minutes',
    downtime: 'Keine', downtime_en: 'None',
    results_onset: '3–10 Tage', results_onset_en: '3–10 days',
    results_duration: '4–6 Monate', results_duration_en: '4–6 months',
    price_from: 'Auf Anfrage', price_from_en: 'On request',
    aftercare_de: 'Aufrechte Haltung für einige Stunden, keine Massage der Region, kein Sport oder Sauna am Behandlungstag.',
    aftercare_en: 'Remain upright for several hours, no massage of the area, no exercise or sauna on the day of treatment.',
    risks_de: 'Leichte Rötung, Schwellung oder Bluterguss an den Einstichstellen möglich. Selten vorübergehendes Hängen des Augenlids.',
    risks_en: 'Mild redness, swelling, or bruising at the injection sites is possible. Rarely, temporary eyelid drooping.',
    contraindications_de: 'Nicht geeignet bei bestimmten neuromuskulären Erkrankungen, in Schwangerschaft und Stillzeit sowie bei Infektionen im Behandlungsbereich.',
    contraindications_en: 'Not suitable for certain neuromuscular disorders, during pregnancy and breastfeeding, or in the presence of infections in the treatment area.',
    faqs: [
      { q_de: 'Kann die Zornesfalte ganz verschwinden?', a_de: 'Die dynamische Faltenbildung wird deutlich reduziert. Bereits sehr tief eingegrabene Falten in Ruhe können in Kombination mit weiteren Verfahren behandelt werden.', q_en: 'Can the frown line disappear completely?', a_en: 'Dynamic line formation is significantly reduced. Very deeply etched static lines may be addressed in combination with other procedures.' },
    ],
    medical_reviewer: 'Dr. med. Barbara Matziris',
  },
  kraehenfuesse: {
    slug: 'kraehenfuesse', category: 'botulinumtoxin', categoryPath: '/behandlungen/botulinumtoxin',
    title_de: 'Krähenfüsse', title_en: "Crow's Feet",
    meta_title_de: 'Krähenfüsse behandeln | Botulinumtoxin Zürich | Aurea Aesthetics',
    meta_title_en: "Crow's Feet Treatment | Botulinum Toxin Zurich | Aurea Aesthetics",
    meta_description_de: 'Behandlung feiner Fältchen am äusseren Augenwinkel mit Botulinumtoxin in Zürich — für einen wachen, natürlichen Blick.',
    meta_description_en: "Treatment of fine lines at the outer eye corner with botulinum toxin in Zurich — for a bright, natural gaze.",
    lead_de: 'Feine Fältchen am äusseren Augenwinkel entstehen vor allem beim Lachen. Eine behutsame Behandlung glättet die Linien, ohne das natürliche Lachen einzuschränken.',
    lead_en: "Fine lines at the outer eye corner form mainly when smiling. Careful treatment smooths the lines without restricting natural smiling.",
    image_url: 'https://media.base44.com/images/public/6a6b131f6cc49b3ee60e929e/9147ba321_generated_image.png',
    indications: ['Feine Linien am äusseren Augenwinkel beim Lachen', 'Wunsch nach einem wacheren Blick', 'Vorbeugende Behandlung bei beginnender Faltenbildung'],
    mechanism_de: 'Die Behandlung reduziert gezielt die Aktivität des äusseren Anteils des Musculus orbicularis oculi, wodurch die strahlenförmigen Fältchen sichtbar geglättet werden.',
    mechanism_en: 'The treatment specifically reduces activity in the outer portion of the orbicularis oculi muscle, visibly smoothing the radiating lines.',
    procedure_de: 'Feine Injektionen erfolgen oberflächennah an mehreren Punkten seitlich des Auges. Die Behandlung dauert 15 bis 20 Minuten und ist gut verträglich.',
    procedure_en: 'Fine, superficial injections are placed at several points beside the eye. The treatment takes 15 to 20 minutes and is well tolerated.',
    duration: '15–20 Minuten', duration_en: '15–20 minutes',
    downtime: 'Keine', downtime_en: 'None',
    results_onset: '3–10 Tage', results_onset_en: '3–10 days',
    results_duration: '3–5 Monate', results_duration_en: '3–5 months',
    price_from: 'Auf Anfrage', price_from_en: 'On request',
    aftercare_de: 'Aufrechte Haltung für einige Stunden, kein Reiben der Augenregion, kein Sport oder Sauna am Behandlungstag.',
    aftercare_en: 'Remain upright for several hours, avoid rubbing the eye area, no exercise or sauna on the day of treatment.',
    risks_de: 'Leichte Schwellung oder Bluterguss möglich. Selten vorübergehende Asymmetrie des Lidschlusses.',
    risks_en: 'Mild swelling or bruising is possible. Rarely, temporary asymmetry of eyelid closure.',
    contraindications_de: 'Nicht geeignet bei bestimmten neuromuskulären Erkrankungen, in Schwangerschaft und Stillzeit sowie bei Infektionen im Behandlungsbereich.',
    contraindications_en: 'Not suitable for certain neuromuscular disorders, during pregnancy and breastfeeding, or in the presence of infections in the treatment area.',
    faqs: [
      { q_de: 'Beeinträchtigt die Behandlung mein Lachen?', a_de: 'Bei sorgfältiger, niedriger Dosierung bleibt das natürliche Lachen erhalten — Ziel ist die Reduktion der Fältchen, nicht die Einschränkung der Mimik.', q_en: 'Will the treatment affect my smile?', a_en: 'With careful, low dosing, natural smiling is preserved — the goal is reducing the lines, not restricting expression.' },
    ],
    medical_reviewer: 'Dr. med. Barbara Matziris',
  },
  'masseter-zaehneknirschen': {
    slug: 'masseter-zaehneknirschen', category: 'botulinumtoxin', categoryPath: '/behandlungen/botulinumtoxin',
    title_de: 'Masseter und Zähneknirschen', title_en: 'Masseter & Teeth Grinding',
    meta_title_de: 'Masseter-Behandlung & Zähneknirschen | Zürich | Aurea Aesthetics',
    meta_title_en: 'Masseter Treatment & Teeth Grinding | Zurich | Aurea Aesthetics',
    meta_description_de: 'Behandlung des Kaumuskels bei Zähneknirschen und Kieferverspannung mit Botulinumtoxin in Zürich — für Entlastung und schlankere Kieferkontur.',
    meta_description_en: 'Masseter muscle treatment for teeth grinding and jaw tension with botulinum toxin in Zurich — for relief and a slimmer jawline contour.',
    lead_de: 'Eine Überaktivität des Kaumuskels führt häufig zu nächtlichem Zähneknirschen, Kieferverspannung und Kopfschmerzen — und kann zusätzlich zu einer breiteren Unterkieferkontur führen.',
    lead_en: 'Overactivity of the masseter muscle often causes nighttime teeth grinding, jaw tension, and headaches — and can also widen the lower-jaw contour.',
    image_url: 'https://media.base44.com/images/public/6a6b131f6cc49b3ee60e929e/9147ba321_generated_image.png',
    indications: ['Nächtliches Zähneknirschen (Bruxismus)', 'Kieferverspannung und begleitende Kopfschmerzen', 'Wunsch nach schlankerer Unterkieferkontur'],
    mechanism_de: 'Botulinumtoxin reduziert gezielt die Überaktivität des Musculus masseter. Dies entlastet das Kiefergelenk, lindert Verspannungen und kann über mehrere Monate zu einer feineren Unterkieferkontur führen.',
    mechanism_en: 'Botulinum toxin specifically reduces overactivity of the masseter muscle. This relieves strain on the jaw joint, eases tension, and can lead to a finer lower-jaw contour over several months.',
    procedure_de: 'Nach Tastbefund des Muskels bei Anspannung erfolgt die Injektion beidseitig in mehreren Punkten. Die Behandlung dauert 20 bis 30 Minuten.',
    procedure_en: 'After palpating the muscle under tension, injections are placed at several points on both sides. The treatment takes 20 to 30 minutes.',
    duration: '20–30 Minuten', duration_en: '20–30 minutes',
    downtime: 'Keine', downtime_en: 'None',
    results_onset: '1–3 Wochen', results_onset_en: '1–3 weeks',
    results_duration: '4–6 Monate', results_duration_en: '4–6 months',
    price_from: 'Auf Anfrage', price_from_en: 'On request',
    aftercare_de: 'Vermeiden Sie starkes Kauen (z. B. Kaugummi) in den ersten Tagen. Leichte Druckempfindlichkeit im Kaumuskel ist normal.',
    aftercare_en: 'Avoid vigorous chewing (e.g. gum) for the first few days. Mild tenderness in the masseter muscle is normal.',
    risks_de: 'Vorübergehende Kauschwäche bei zu hoher Dosierung möglich, daher schrittweise, individuelle Dosierung. Leichte Schwellung oder Bluterguss möglich.',
    risks_en: 'Temporary chewing weakness is possible if dosed too high, which is why dosing is stepwise and individualised. Mild swelling or bruising is possible.',
    contraindications_de: 'Nicht geeignet bei bestimmten neuromuskulären Erkrankungen, in Schwangerschaft und Stillzeit sowie bei bestehenden Kaumuskelerkrankungen ohne vorherige Abklärung.',
    contraindications_en: 'Not suitable for certain neuromuscular disorders, during pregnancy and breastfeeding, or for existing masseter muscle conditions without prior assessment.',
    faqs: [
      { q_de: 'Wie lange dauert es, bis sich der Kiefer schlanker zeigt?', a_de: 'Die konturierende Wirkung zeigt sich meist nach 4 bis 8 Wochen, da sich der Muskel über diese Zeit zurückbildet.', q_en: 'How long until the jaw appears slimmer?', a_en: 'The contouring effect usually becomes visible after 4 to 8 weeks, as the muscle gradually reduces in size.' },
      { q_de: 'Hilft die Behandlung wirklich gegen Knirschen?', a_de: 'Viele Patientinnen und Patienten berichten von deutlich weniger nächtlichem Knirschen und Verspannung. Bei ausgeprägtem Bruxismus empfehlen wir zusätzlich eine zahnärztliche Abklärung.', q_en: 'Does the treatment really help with grinding?', a_en: 'Many patients report significantly less nighttime grinding and tension. For pronounced bruxism, we also recommend a dental evaluation.' },
    ],
    medical_reviewer: 'Dr. med. Nadine Dovi-Akue',
  },
  schwitzen: {
    slug: 'schwitzen', category: 'botulinumtoxin', categoryPath: '/behandlungen/botulinumtoxin',
    title_de: 'Übermässiges Schwitzen', title_en: 'Excessive Sweating',
    meta_title_de: 'Behandlung bei übermässigem Schwitzen | Zürich | Aurea Aesthetics',
    meta_title_en: 'Excessive Sweating Treatment | Zurich | Aurea Aesthetics',
    meta_description_de: 'Behandlung der Hyperhidrose in Achseln, Händen oder Füssen mit Botulinumtoxin in Zürich — deutliche Reduktion der Schweissproduktion über Monate.',
    meta_description_en: 'Treatment of hyperhidrosis in the underarms, hands, or feet with botulinum toxin in Zurich — significant reduction in sweat production for months.',
    lead_de: 'Übermässiges Schwitzen (Hyperhidrose) kann den Alltag deutlich einschränken. Eine gezielte Behandlung reduziert die Aktivität der Schweissdrüsen spürbar und über Monate.',
    lead_en: 'Excessive sweating (hyperhidrosis) can significantly limit daily life. Targeted treatment noticeably reduces sweat gland activity for months.',
    image_url: 'https://media.base44.com/images/public/6a6b131f6cc49b3ee60e929e/9147ba321_generated_image.png',
    indications: ['Übermässiges Schwitzen in den Achseln', 'Übermässiges Schwitzen an Händen oder Füssen', 'Alltägliche Einschränkung durch Hyperhidrose'],
    mechanism_de: 'Botulinumtoxin blockiert die Nervensignale, die die Schweissdrüsen zur Produktion anregen. Die Schweissproduktion in der behandelten Region wird dadurch deutlich reduziert.',
    mechanism_en: 'Botulinum toxin blocks the nerve signals that stimulate sweat gland activity. Sweat production in the treated area is thereby significantly reduced.',
    procedure_de: 'Nach Bestimmung der betroffenen Fläche (ggf. mittels Jod-Stärke-Test) erfolgen zahlreiche kleine, oberflächliche Injektionen im gesamten Areal. Die Behandlung dauert 30 bis 45 Minuten.',
    procedure_en: 'After determining the affected area (optionally using an iodine-starch test), numerous small, superficial injections are placed across the entire region. The treatment takes 30 to 45 minutes.',
    duration: '30–45 Minuten', duration_en: '30–45 minutes',
    downtime: 'Keine', downtime_en: 'None',
    results_onset: '1–2 Wochen', results_onset_en: '1–2 weeks',
    results_duration: '6–9 Monate', results_duration_en: '6–9 months',
    price_from: 'Auf Anfrage', price_from_en: 'On request',
    aftercare_de: 'Keine besonderen Einschränkungen. Sport und Sauna sollten am Behandlungstag vermieden werden.',
    aftercare_en: 'No particular restrictions. Exercise and sauna should be avoided on the day of treatment.',
    risks_de: 'Leichte Rötung oder Druckempfindlichkeit an den Einstichstellen möglich. Bei Handbehandlung selten vorübergehende Griffkraftminderung.',
    risks_en: 'Mild redness or tenderness at the injection sites is possible. For hand treatment, rarely a temporary reduction in grip strength.',
    contraindications_de: 'Nicht geeignet bei bestimmten neuromuskulären Erkrankungen, in Schwangerschaft und Stillzeit sowie bei Infektionen im Behandlungsbereich.',
    contraindications_en: 'Not suitable for certain neuromuscular disorders, during pregnancy and breastfeeding, or in the presence of infections in the treatment area.',
    faqs: [
      { q_de: 'Wie lange hält die Wirkung an?', a_de: 'Die Wirkung hält je nach Körperregion in der Regel 6 bis 9 Monate an, an den Achseln oft am längsten.', q_en: 'How long does the effect last?', a_en: 'Depending on the body region, the effect typically lasts 6 to 9 months, often longest in the underarms.' },
    ],
    medical_reviewer: 'Dr. med. Nadine Dovi-Akue',
  },
  lippenbehandlung: {
    slug: 'lippenbehandlung', category: 'hyaluron-konturierung', categoryPath: '/behandlungen/hyaluron-konturierung',
    title_de: 'Lippenbehandlung', title_en: 'Lip Treatment',
    meta_title_de: 'Lippenbehandlung mit Hyaluronsäure | Zürich | Aurea Aesthetics',
    meta_title_en: 'Lip Treatment with Hyaluronic Acid | Zurich | Aurea Aesthetics',
    meta_description_de: 'Natürliche Lippenkonturierung mit Hyaluronsäure in Zürich — individuell abgestimmt auf Ihre Gesichtsproportionen.',
    meta_description_en: 'Natural lip contouring with hyaluronic acid in Zurich — individually tailored to your facial proportions.',
    lead_de: 'Feine Konturierung und dezenter Volumenaufbau lassen die Lippen ausgewogen wirken, ohne die individuelle Anatomie zu überschreiben.',
    lead_en: 'Fine contouring and subtle volume enhancement create balanced lips without overriding individual anatomy.',
    image_url: 'https://media.base44.com/images/public/6a6b131f6cc49b3ee60e929e/aa2efde7c_generated_image.png',
    indications: ['Wunsch nach mehr Lippenvolumen', 'Ausgleich von Asymmetrien', 'Auffüllen feiner Fältchen um den Mund'],
    mechanism_de: 'Hyaluronsäure wird fein dosiert in die Lippen eingebracht, um Kontur und Volumen gezielt zu formen. Die Substanz bindet zusätzlich Feuchtigkeit im Gewebe.',
    mechanism_en: 'Hyaluronic acid is finely dosed into the lips to shape contour and volume. The substance also binds moisture within the tissue.',
    procedure_de: 'Nach Analyse der Lippenform und Absprache Ihrer Wünsche erfolgt die Injektion mit feinsten Kanülen. Eine betäubende Creme kann vorab aufgetragen werden. Die Behandlung dauert etwa 30 Minuten.',
    procedure_en: 'After analysing lip shape and discussing your wishes, the treatment is administered using the finest cannulas. A numbing cream may be applied beforehand. The treatment takes about 30 minutes.',
    duration: '30 Minuten', duration_en: '30 minutes',
    downtime: '1–3 Tage leichte Schwellung', downtime_en: '1–3 days mild swelling',
    results_onset: 'Sofort', results_onset_en: 'Immediate',
    results_duration: '6–12 Monate', results_duration_en: '6–12 months',
    price_from: 'Auf Anfrage', price_from_en: 'On request',
    aftercare_de: 'Leichte Schwellung in den ersten Tagen ist normal. Vermeiden Sie in den ersten 48 Stunden starke Hitze, Sport und Alkohol.',
    aftercare_en: 'Mild swelling in the first few days is normal. Avoid intense heat, exercise, and alcohol for the first 48 hours.',
    risks_de: 'Schwellung, Rötung oder kleine Blutergüsse sind häufig und klingen innerhalb weniger Tage ab. Selten Knötchenbildung.',
    risks_en: 'Swelling, redness, or small bruises are common and subside within a few days. Rarely, small nodules.',
    contraindications_de: 'Nicht geeignet bei akuten Infektionen im Mundbereich, in der Schwangerschaft und Stillzeit sowie bei bekannter Hyaluronsäure-Unverträglichkeit.',
    contraindications_en: 'Not suitable for acute infections in the mouth area, during pregnancy and breastfeeding, or with known hyaluronic acid intolerance.',
    faqs: [
      { q_de: 'Wirken die Lippen danach künstlich?', a_de: 'Ziel ist ein ausgewogenes, der eigenen Anatomie entsprechendes Ergebnis. Wir arbeiten mit zurückhaltender Dosierung und bauen Volumen bei Bedarf über mehrere Sitzungen auf.', q_en: 'Will the lips look artificial afterwards?', a_en: 'The goal is a balanced result that suits your own anatomy. We work with restrained dosing and build volume gradually over multiple sessions if needed.' },
    ],
    medical_reviewer: 'Dr. med. Barbara Matziris',
  },
  jawline: {
    slug: 'jawline', category: 'hyaluron-konturierung', categoryPath: '/behandlungen/hyaluron-konturierung',
    title_de: 'Jawline', title_en: 'Jawline',
    meta_title_de: 'Jawline-Konturierung mit Hyaluronsäure | Zürich | Aurea Aesthetics',
    meta_title_en: 'Jawline Contouring with Hyaluronic Acid | Zurich | Aurea Aesthetics',
    meta_description_de: 'Definierte Kieferlinie durch Hyaluronsäure-Konturierung in Zürich — individuell geplant für ein klareres Profil.',
    meta_description_en: 'A defined jawline through hyaluronic acid contouring in Zurich — individually planned for a clearer profile.',
    lead_de: 'Eine gezielte Konturierung entlang des Unterkiefers definiert die Gesichtslinie und schafft ein klareres, gestrafftes Profil.',
    lead_en: 'Targeted contouring along the lower jaw defines the facial line and creates a clearer, more sculpted profile.',
    image_url: 'https://media.base44.com/images/public/6a6b131f6cc49b3ee60e929e/aa2efde7c_generated_image.png',
    indications: ['Wunsch nach klarerer Kieferlinie', 'Ausgleich einer weichen Unterkieferkontur', 'Verbesserung des seitlichen Profils'],
    mechanism_de: 'Hyaluronsäure wird entlang des Unterkieferknochens platziert, um die Kontur zu stützen und zu definieren, ohne das Gesicht zu verbreitern.',
    mechanism_en: 'Hyaluronic acid is placed along the jawbone to support and define the contour without widening the face.',
    procedure_de: 'Nach Analyse des Profils in Ruhe und Bewegung erfolgt die Injektion entlang der Kieferlinie mit Kanüle oder feiner Nadel. Die Behandlung dauert 30 bis 45 Minuten.',
    procedure_en: 'After analysing the profile at rest and in motion, injections are placed along the jawline using a cannula or fine needle. The treatment takes 30 to 45 minutes.',
    duration: '30–45 Minuten', duration_en: '30–45 minutes',
    downtime: '2–4 Tage leichte Schwellung', downtime_en: '2–4 days mild swelling',
    results_onset: 'Sofort, endgültig nach 2 Wochen', results_onset_en: 'Immediate, final after 2 weeks',
    results_duration: '9–14 Monate', results_duration_en: '9–14 months',
    price_from: 'Auf Anfrage', price_from_en: 'On request',
    aftercare_de: 'Leichte Schwellung und Druckempfindlichkeit sind in den ersten Tagen normal. Vermeiden Sie starke Hitze und intensiven Sport für 48 Stunden.',
    aftercare_en: 'Mild swelling and tenderness are normal for the first few days. Avoid intense heat and vigorous exercise for 48 hours.',
    risks_de: 'Schwellung, Rötung oder Blutergüsse möglich. Selten Asymmetrien, die nachkorrigiert werden können.',
    risks_en: 'Swelling, redness, or bruising is possible. Rarely, asymmetries that can be corrected in a follow-up.',
    contraindications_de: 'Nicht geeignet bei akuten Infektionen im Behandlungsbereich, in Schwangerschaft und Stillzeit sowie bei bekannter Hyaluronsäure-Unverträglichkeit.',
    contraindications_en: 'Not suitable for acute infections in the treatment area, during pregnancy and breastfeeding, or with known hyaluronic acid intolerance.',
    faqs: [
      { q_de: 'Wird das Gesicht dadurch breiter?', a_de: 'Bei fachgerechter Platzierung entlang des Knochens wirkt die Kieferlinie definierter, nicht breiter — die Konturierung folgt der individuellen Anatomie.', q_en: 'Will this make the face wider?', a_en: 'With expert placement along the bone, the jawline appears more defined, not wider — contouring follows individual anatomy.' },
    ],
    medical_reviewer: 'Dr. med. Nadine Dovi-Akue',
  },
  prp: {
    slug: 'prp', category: 'hautqualitaet-regeneration', categoryPath: '/behandlungen/hautqualitaet-regeneration',
    title_de: 'PRP', title_en: 'PRP',
    meta_title_de: 'PRP-Behandlung (Eigenblut) | Zürich | Aurea Aesthetics',
    meta_title_en: 'PRP Treatment (Platelet-Rich Plasma) | Zurich | Aurea Aesthetics',
    meta_description_de: 'PRP-Behandlung mit körpereigenem, thrombozytenreichem Plasma in Zürich — zur Anregung der Hautregeneration.',
    meta_description_en: 'PRP treatment with the body\'s own platelet-rich plasma in Zurich — to stimulate skin regeneration.',
    lead_de: 'Aus einer kleinen Blutentnahme wird thrombozytenreiches Plasma gewonnen und gezielt in die Haut eingebracht, um körpereigene Regenerationsprozesse anzuregen.',
    lead_en: 'Platelet-rich plasma is obtained from a small blood draw and introduced into the skin to stimulate the body\'s own regeneration processes.',
    image_url: 'https://media.base44.com/images/public/6a6b131f6cc49b3ee60e929e/178c12a52_generated_image.png',
    indications: ['Müde, fahle Hautqualität', 'Feine Linien und verminderte Elastizität', 'Wunsch nach einem rein körpereigenen Verfahren'],
    mechanism_de: 'Aus einer kleinen Blutprobe wird in einer Zentrifuge das thrombozytenreiche Plasma isoliert. Die enthaltenen Wachstumsfaktoren regen bei Injektion in die Haut die körpereigene Kollagen- und Zellregeneration an.',
    mechanism_en: 'From a small blood sample, platelet-rich plasma is isolated using a centrifuge. When injected into the skin, the growth factors it contains stimulate the body\'s own collagen and cell regeneration.',
    procedure_de: 'Nach einer kleinen Blutentnahme wird das Plasma aufbereitet und anschliessend mit feinen Nadeln in die Haut eingebracht. Die Behandlung dauert etwa 45 Minuten.',
    procedure_en: 'After a small blood draw, the plasma is processed and then introduced into the skin using fine needles. The treatment takes about 45 minutes.',
    duration: '45 Minuten', duration_en: '45 minutes',
    downtime: '1–2 Tage leichte Rötung', downtime_en: '1–2 days mild redness',
    results_onset: 'Nach mehreren Wochen', results_onset_en: 'After several weeks',
    results_duration: '6–9 Monate', results_duration_en: '6–9 months',
    price_from: 'Auf Anfrage', price_from_en: 'On request',
    aftercare_de: 'Leichte Rötung und Schwellung sind in den ersten Tagen normal. Direkte Sonneneinstrahlung und Sauna sollten für einige Tage vermieden werden.',
    aftercare_en: 'Mild redness and swelling are normal for the first few days. Avoid direct sun exposure and sauna for several days.',
    risks_de: 'Rötung, Schwellung oder kleine Blutergüsse an den Einstichstellen möglich. Da körpereigenes Material verwendet wird, ist das allergische Risiko sehr gering.',
    risks_en: 'Redness, swelling, or small bruises at the injection sites are possible. Since the body\'s own material is used, allergic risk is very low.',
    contraindications_de: 'Nicht geeignet bei bestimmten Blutgerinnungsstörungen, akuten Infektionen sowie in bestimmten Blutbild-Konstellationen — Abklärung im Beratungsgespräch.',
    contraindications_en: 'Not suitable for certain blood clotting disorders, acute infections, or specific blood count conditions — assessed during consultation.',
    faqs: [
      { q_de: 'Ist PRP ein rein natürliches Verfahren?', a_de: 'Ja, es wird ausschliesslich körpereigenes Material verwendet — es kommen keine Fremdsubstanzen zum Einsatz.', q_en: 'Is PRP a fully natural procedure?', a_en: 'Yes, only your own body\'s material is used — no foreign substances are involved.' },
    ],
    medical_reviewer: 'Dr. med. Barbara Matziris',
  },
  microneedling: {
    slug: 'microneedling', category: 'hautqualitaet-regeneration', categoryPath: '/behandlungen/hautqualitaet-regeneration',
    title_de: 'Microneedling', title_en: 'Microneedling',
    meta_title_de: 'Microneedling-Behandlung | Zürich | Aurea Aesthetics',
    meta_title_en: 'Microneedling Treatment | Zurich | Aurea Aesthetics',
    meta_description_de: 'Microneedling in Zürich zur Verfeinerung der Hautstruktur — regt Kollagenbildung an und verbessert die Wirkstoffaufnahme.',
    meta_description_en: 'Microneedling in Zurich to refine skin texture — stimulates collagen formation and improves active-ingredient absorption.',
    lead_de: 'Feinste Nadeln setzen gezielte Mikroverletzungen in der Haut, die körpereigene Reparaturprozesse und die Kollagenbildung anregen.',
    lead_en: 'Fine needles create controlled micro-injuries in the skin that stimulate the body\'s own repair processes and collagen formation.',
    image_url: 'https://media.base44.com/images/public/6a6b131f6cc49b3ee60e929e/178c12a52_generated_image.png',
    indications: ['Grobporige oder unebene Hautstruktur', 'Feine Linien und leichte Närbchen', 'Wunsch nach verbesserter Wirkstoffaufnahme'],
    mechanism_de: 'Ein medizinisches Needling-Gerät setzt feinste, kontrollierte Mikroverletzungen in der obersten Hautschicht. Dies löst einen natürlichen Heilungsprozess aus, der die Kollagen- und Elastinbildung anregt.',
    mechanism_en: 'A medical needling device creates fine, controlled micro-injuries in the uppermost skin layer. This triggers a natural healing process that stimulates collagen and elastin production.',
    procedure_de: 'Nach Reinigung der Haut und Auftragen einer betäubenden Creme wird die Behandlung flächig über das Gesicht durchgeführt. Die Behandlung dauert 30 bis 45 Minuten.',
    procedure_en: 'After cleansing the skin and applying a numbing cream, the treatment is performed across the face. The treatment takes 30 to 45 minutes.',
    duration: '30–45 Minuten', duration_en: '30–45 minutes',
    downtime: '1–3 Tage Rötung', downtime_en: '1–3 days redness',
    results_onset: 'Nach mehreren Wochen', results_onset_en: 'After several weeks',
    results_duration: 'Kumulativ über mehrere Sitzungen', results_duration_en: 'Cumulative over several sessions',
    price_from: 'Auf Anfrage', price_from_en: 'On request',
    aftercare_de: 'Die Haut zeigt sich in den ersten Tagen gerötet, ähnlich einem leichten Sonnenbrand. Sonnenschutz ist in den folgenden Tagen besonders wichtig.',
    aftercare_en: 'The skin appears red for the first few days, similar to mild sunburn. Sun protection is especially important in the following days.',
    risks_de: 'Rötung, leichte Schwellung und Spannungsgefühl sind häufig und klingen innerhalb weniger Tage ab. Selten Pigmentveränderungen.',
    risks_en: 'Redness, mild swelling, and a feeling of tightness are common and subside within a few days. Rarely, pigmentation changes.',
    contraindications_de: 'Nicht geeignet bei aktiven Hautinfektionen, Ekzemen im Behandlungsbereich, in der Schwangerschaft ohne vorherige Abklärung sowie bei Neigung zu Keloidbildung.',
    contraindications_en: 'Not suitable for active skin infections, eczema in the treatment area, pregnancy without prior assessment, or a tendency toward keloid formation.',
    faqs: [
      { q_de: 'Wie viele Sitzungen sind empfehlenswert?', a_de: 'Für ein sichtbares Ergebnis empfehlen wir in der Regel eine Serie von 3 bis 4 Sitzungen im Abstand von 4 bis 6 Wochen.', q_en: 'How many sessions are recommended?', a_en: 'For a visible result, we generally recommend a series of 3 to 4 sessions spaced 4 to 6 weeks apart.' },
    ],
    medical_reviewer: 'Dr. med. Nadine Dovi-Akue',
  },
};
